name: CICron
on:
  schedule:
  - cron: '0 0 * * *'

jobs:
  build:
    name: Multi-Arch Cron Build
    runs-on: ubuntu-latest
    if: "!contains(github.ref, 'coverity_scan')"
    strategy:
      matrix:
        DOCKER_IMAGE: [
          "ubuntu-20.04.arm32v7",
          "ubuntu-20.04.arm64v8",
          "fedora-32.ppc64le"
        ]
    steps:
      - name: Setup QEMU
        run: |
            sudo apt-get update
            sudo apt-get install qemu binfmt-support qemu-user-static
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Launch Action
        uses:
          tpm2-software/ci/runCI@main
        with:
          PROJECT_NAME: ${{ github.event.repository.name }}
          DOCKER_IMAGE: ${{ matrix.docker_image }}
          CC: ${{ matrix.compiler }}
          MULTIARCH_BUILD: true
      - name: failure
        if: ${{ failure() }}
        run: cat build/test-suite.log || true