name: CI
on:
  [push, pull_request]
jobs:
  build-test:
    runs-on: ubuntu-latest
    if: "!contains(github.ref, 'coverity_scan')"
    strategy:
      matrix:
        docker_image: [ubuntu-18.04, ubuntu-20.04, fedora-30, opensuse-leap, fedora-32, ubuntu-22.04]
        compiler: [gcc, clang]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Launch Action
        uses:
          tpm2-software/ci/runCI@main
        with:
          PROJECT_NAME: ${{ github.event.repository.name }}
          DOCKER_IMAGE: ${{ matrix.docker_image }}
          CC: ${{ matrix.compiler }}
      - name: failure
        if: ${{ failure() }}
        run: cat build/test-suite.log || true
  master-tss-build-test:
    runs-on: ubuntu-latest
    if: "!contains(github.ref, 'coverity_scan')"
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Launch Action
        uses:
          tpm2-software/ci/runCI@main
        with:
          PROJECT_NAME: ${{ github.event.repository.name }}
          DOCKER_IMAGE: ubuntu-18.04
          CC: ${{ matrix.compiler }}
          TPM2_TSS_VERSION: master
          GIT_FULL_CLONE: true
      - name: failure
        if: ${{ failure() }}
        run: cat build/test-suite.log || true
  multi-arch:
    runs-on: ubuntu-latest
    if: "!contains(github.ref, 'coverity_scan')"
    strategy:
      matrix:
        DOCKER_IMAGE: [
          "ubuntu-20.04.arm32v7",
          "ubuntu-20.04.arm64v8",
          "fedora-32.ppc64le"
        ]
    steps:
      - name: Setup QEMU
        run: |
          sudo apt-get update
          sudo apt-get install qemu binfmt-support qemu-user-static
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Launch Container
        env:
          DOCKER_IMAGE: ${{ matrix.docker_image }}
          CC: ${{ matrix.compiler }}
        run: ./.ci/ci.run
      - name: failure
        if: ${{ failure() }}
        run: cat build/test-suite.log || true
  coverage-test:
    runs-on: ubuntu-latest
    if: "!contains(github.ref, 'coverity_scan')"
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Launch Action
        uses:
          tpm2-software/ci/runCI@main
        with:
          PROJECT_NAME: ${{ github.event.repository.name }}
          ENABLE_COVERAGE: true
          DOCKER_IMAGE: ubuntu-18.04
          CC: gcc
      - name: failure cat build logs
        if: ${{ failure() }}
        run: cat build/test-suite.log || true
      - name: failure cat compatibility_testbuild logs
        if: ${{ failure() }}
        run: cat compatibility_testbuild/test-suite.log || true
  coverity-test:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'coverity_scan')
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Launch Coverity Action
        uses:
          tpm2-software/ci/coverityScan@main
        with:
          PROJECT_NAME: ${{ github.event.repository.name }}
          REPO_BRANCH: ${{ github.ref }}
          REPO_NAME: ${{ github.repository }}
          ENABLE_COVERITY: true
          DOCKER_IMAGE: ubuntu-18.04
          CC: gcc
          COVERITY_SCAN_TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
          COVERITY_SUBMISSION_EMAIL: william.c.roberts@gmail.com
      - name: failure
        if: ${{ failure() }}
        run: cat build/test-suite.log || true
